version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./manage.py runserver 0.0.0.0:8000
    links:
      - db
      - redis
    depends_on:
      - db
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./sharing/:/src/

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A sharing worker -l info --loglevel=INFO
    volumes:
      - ./sharing/:/src/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A sharing beat -l info --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./sharing/:/src/
    depends_on:
      - redis
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_DATABASE: sharingdb
      MYSQL_USER: sharring_user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306

  redis:
    image: redis:alpine
    restart: unless-stopped