version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - 88:80
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./sharing/static/:/static
      - ./sharing/media/:/media

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi sharing_uwsgi.ini
    env_file:
      - .envs
    links:
      - db
      - redis
    depends_on:
      - db
    volumes:
      - ./sharing/:/src/

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A sharing worker -l info --loglevel=INFO
    env_file:
      - .envs
    volumes:
      - ./sharing/:/src/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A sharing beat -l info --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .envs
    volumes:
      - ./sharing/:/src/
    depends_on:
      - redis
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_DATABASE: sharingdb
      MYSQL_USER: sharring_user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306

  redis:
    image: redis:alpine
    restart: unless-stopped